### ISSUE TITLE
Albert's Issues with 0.1.2

### ISSUE THREAD

**Issue by DBendit** [andrewrk/Secure-WordVault#2]
1. The search box appears to be displayed when I first download the program but is then hidden by default on all saved documents.
2. It takes about 2 seconds on my little netbook to open the program (even without any text saved). Can we have a tiny splash screen that pops up just so users know it's actually doing something? 
3. Can we make the first screen, the password input form, appear in the taskbar? As it is, I have to ALT + TAB to find it and that won't be easy for people who don't know how to do that.
4. Can we get rid of the solid cursor in the Find box on startup?
5. Find and Replace is difficult to use. There are 4 arrows, and we need to have 3 buttons instead: "Find Next"   "Replace"   "Replace All" 
   One idea to save space is to put the "Replace ________  With _______" on the top line and then add a new line under it with the 3 buttons.
   Actually, I'm not convinced we need to have this function. If it gets to be too much of a hassle, let's just remove it. 
6. On program startup, Undo and Redo should be disabled if there is nothing to undo/redo
7. Can File > New actually open a new window without requiring me to save/discard changes? I realize this isn't the same as Windows Notepad, but it's a little friendlier especially if a user wants to copy something from the current document into a new one.
8. After File > Save As... there needs to be some mention of the password. Any suggestions as to whether: 
   1. the user should input a password (choose a new password) 
   2. choose whether to change the password or keep the old one
   3. a window informs the user that the password for the old file has been transfered to the new file
   4. any other ideas?

**Comment by DBendit** [comment]
1, 3, 4, and 6 have been addressed

**Comment by DBendit** [comment]
Also addressed: All tweaks from PDF except:
Meta-info in the EXE
CAPS LOCK warning on password dialogs

**Comment by thejoshwolfe** [comment]
Unresolved issues from this list:
1. #4 startup time is too long
2. Find and Replace is difficult to use.
3. #5 File > New should open a new window.
4. File > Save As... needs to mention the password. One of these:
   1. the user should input a password (choose a new password)
   2. #6 choose whether to change the password or keep the old one
   3. a window informs the user that the password for the old file has been transfered to the new file
   4. any other ideas?

Any issue above that does not have another issue spawned for it I vote gets abandoned.
