### ISSUE TITLE
Issue with specific-length plaintext

### ISSUE THREAD

**Issue by DBendit** [andrewrk/Secure-WordVault#3]
I don't feel like looking up the details right now, but we had an issue with plaintext of a specific length corrupting the ciphertext. I feel like it was 31 characters or something arbitrary like that. If you're going to resurrect this thing, we may as well document the known bugs :)

**Comment by thejoshwolfe** [comment]
sounds like issue #1

**Comment by DBendit** [comment]
IIRC, it was a different issue. If you have over the arbitrary amount of characters, it works fine. Same with small olaintexts. But if you have that exact number of characters, it fails.

I could also be entirely incorrect. I haven't looked at this in a year and a half.
